HashFunctions_test_OBJS  = HashFunctions_test.o $(MODULES)/HashFunctions/HashFunctions.o
BloomFilter_test_OBJS  = BloomFilter_test.o $(MODULES)/BloomFilter/BloomFilter.o $(MODULES)/HashFunctions/HashFunctions.o
List_test_OBJS = List_test.o $(MODULES)/List/List.o
Queue_test_OBJS = Queue_test.o $(MODULES)/Queue/Queue.o
RBTree_test_OBJS = RBTree_test.o $(MODULES)/RBTree/RBTree.o
DisJointSet_test_OBJS = DisJointSet_test.o $(MODULES)/DisJointSet/DisJointSet.o
HashTable_withRBT_test_OBJS = HashTable_withRBT_test.o $(MODULES)/HashTable_withRBT/HashTable_withRBT.o $(MODULES)/RBTree/RBTree.o
Comparators_test_OBJS = Comparators_test.o $(MODULES)/Comparators/Comparators.o



# Makefile main body
include ../common.mk
