objectives.a_OBJS = 													\
	$(MODULES)/HashFunctions/HashFunctions.o 							\
	$(MODULES)/BloomFilter/BloomFilter.o 								\
	$(MODULES)/Queue/Queue.o 											\
	$(MODULES)/List/List.o  											\
	$(MODULES)/RBTree/RBTree.o 											\
	$(MODULES)/DisJointSet/DisJointSet.o 								\
	$(MODULES)/Queue/Queue.o 											\
	$(MODULES)/HashTable_withRBT/HashTable_withRBT.o 					\
	$(MODULES)/Comparators/Comparators.o 								\
	$(MODULES)/HeapSort/HeapSort.o 										\
	$(MODULES)/QuickSort/QuickSort.o 									\
	$(MODULES)/MaxHeap/maxHeap.o 										\
	$(MODULES)/HashTable_withList/HashTable_withList.o 					\
	$(MODULES)/HashTable_withBucketstoRBT/HashTable_withBucketstoRBT.o 	\


# 	$(MODULES)/JobScheduler/JobScheduler.o 								\

	

include ../common.mk	
