objectives.a_OBJS = 																\
	$(MODULES)/HashFunctions/HashFunctions.o 											\
	$(MODULES)/BloomFilter/BloomFilter.o 										\

# 	$(MODULES)/RBTree/RBTree.o 											\
# 	$(MODULES)/HashTable/HashTable.o 										\
# 	$(MODULES)/List/list.o  											\
# 	$(MODULES)/DisJointSet/DisJointSet.o 								 	\
# 	$(MODULES)/JobScheduler/JobScheduler.o 								\
# 	$(MODULES)/Queue/Queue.o 											\

	

include ../common.mk	
