objectives.a_OBJS = 													\
	$(MODULES)/HashFunctions/HashFunctions.o 							\
	$(MODULES)/BloomFilter/BloomFilter.o 								\
	$(MODULES)/Queue/Queue.o 											\
	$(MODULES)/List/List.o  											\
	$(MODULES)/RBTree/RBTree.o 											\
	$(MODULES)/DisJointSet/DisJointSet.o 								\
	$(MODULES)/Queue/Queue.o 											\
	$(MODULES)/HashTable_withRBT/HashTable.o 							\


include ../common.mk	
